resolver: lts-8.18
packages:
  - '.'
  - 'yi/yi-core'
  - 'yi/yi-frontend-vty'
  - 'yi/yi-fuzzy-open'
  - 'yi/yi-intero'
  - 'yi/yi-ireader'
  - 'yi/yi-keymap-vim'
  - 'yi/yi-language'
  - 'yi/yi-misc-modes'
  - 'yi/yi-mode-haskell'
  - 'yi/yi-mode-javascript'
  - 'yi/yi-snippet'
extra-deps:
  - yi-rope-0.10
  - compiler-warnings-0.1.0
  - ghcid-0.6.7
